#!/usr/bin/env -S deno run --allow-read --allow-write

// Generates prompts.ts from prompts/*.md in this directory.
//
// Rationale: swamp's extension bundler flattens additionalFiles to basenames
// and the pulled layout differs from the source layout, so runtime
// Deno.readTextFile on bundled .md files is fragile. Inlining prompts as TS
// string constants sidesteps that entirely — see swamp.club/lab/146.

import { fromFileUrl, join } from "jsr:@std/path@1";

const HERE = fromFileUrl(new URL(".", import.meta.url));
const PROMPTS_DIR = join(HERE, "prompts");
const OUT_PATH = join(HERE, "prompts.ts");

const HEADER =
  `// GENERATED by gen_prompts.ts — do not edit.\n// Run \`deno task gen-prompts\` to regenerate from prompts/*.md.\n`;

function toIdent(name: string): string {
  return name
    .replace(/\.md$/, "")
    .replace(/[^a-zA-Z0-9]+/g, "_")
    .toUpperCase() + "_PROMPT";
}

function escapeTemplate(text: string): string {
  return text
    .replace(/\\/g, "\\\\")
    .replace(/`/g, "\\`")
    .replace(/\$\{/g, "\\${");
}

async function main() {
  const entries = [];
  for await (const entry of Deno.readDir(PROMPTS_DIR)) {
    if (entry.isFile && entry.name.endsWith(".md")) {
      entries.push(entry.name);
    }
  }
  entries.sort();

  const parts: string[] = [HEADER];
  const mapEntries: string[] = [];

  for (const name of entries) {
    const content = await Deno.readTextFile(join(PROMPTS_DIR, name));
    const ident = toIdent(name);
    const key = name.replace(/\.md$/, "");
    parts.push(`\nexport const ${ident} = \`${escapeTemplate(content)}\`;\n`);
    mapEntries.push(`  ${JSON.stringify(key)}: ${ident},`);
  }

  parts.push(
    `\nexport const PROMPTS: Record<string, string> = {\n${
      mapEntries.join("\n")
    }\n};\n`,
  );

  await Deno.writeTextFile(OUT_PATH, parts.join(""));
  console.log(`Wrote ${OUT_PATH} (${entries.length} prompts)`);
}

if (import.meta.main) {
  await main();
}
