// GENERATED by gen_prompts.ts — do not edit.
// Run `deno task gen-prompts` to regenerate from prompts/*.md.

export const GEN_REVIEW_PLAN_PROMPT =
  `You are preparing a review plan for a second reviewer agent.

## PR Context
Read these environment variables for context:
- \`PR_NUMBER\`
- \`PR_TITLE\`
- \`PR_URL\`
- \`PR_BASE_REF\`, \`PR_BASE_SHA\`
- \`PR_HEAD_REF\`, \`PR_HEAD_SHA\`

## Goal
Produce a concise, actionable plan that helps a reviewer inspect the PR.

## Required workflow
1. Inspect only this PR delta (\`$PR_BASE_SHA...$PR_HEAD_SHA\`).
2. Identify changed files and classify each one (new/modified/renamed/deleted).
3. Read repository guidance docs if present (\`AGENTS.md\`).
4. For each changed file, find files it imports or calls, and existing files that solve a similar problem.
5. Call out architectural choices that deviate from existing patterns.
6. Define focused review checks for security, correctness, consistency, and API usage.
7. Decide whether a sequence diagram is required for this PR.

## Output format
Output plain text only (no Markdown code fences), using this exact structure:

Review the PR changes for [brief description tied to PR title and scope].

Read all the following files in parallel before beginning your review:
- [file path or file path:startLine-endLine] - [new/modified/comparison/dependency/guidance — brief reason]
- ...

Include every file the reviewer needs: changed, dependencies, comparisons, and guidance docs. Use line ranges when only a specific section matters.

Architectural choices that deviate from existing patterns:
- [choice and why]

Focus areas:
- Security: [specific concerns]
- Correctness: [logic to verify]
- Performance: [hot paths, queries, async concerns]
- Consistency: [patterns/files to compare against]
- API usage: [external or internal APIs to validate]

Sequence diagram:
- Decision: required | optional
- Reason: [brief rationale tied to runtime/control/data-flow complexity]

## Guidelines
- Call out any security-sensitive code (auth, tokens, credentials)
- Explicitly list similar existing files the reviewer should compare against
- Note any external API usage that should be verified against docs
- Keep descriptions concise but informative
- Omit sections that don't apply
- Do not output anything except the final plan text.
`;

export const JUDGE_PROMPT =
  `You are judging pull request reviews produced by multiple AI models.

## Input
Read the file specified by \`JUDGE_INPUT_FILE\` (defaults to \`judge-input.json\`). It contains a JSON array of per-reviewer outputs, each shaped as:

\`\`\`
{
  "model": string,                // the reviewer's model id (cite this in \`sources\`)
  "summary": string,
  "findings": Finding[],
  "questions": Question[],
  "sequenceDiagram"?: string
}
\`\`\`

## Required workflow
1. Read \`JUDGE_INPUT_FILE\` and parse the JSON array.
2. Collect every \`file\` + \`line\`/\`endLine\` cited across all reviewer findings.
3. Read all cited files in parallel:
   - When a line range is given, read at least that range plus surrounding context.
4. For each finding raised by any reviewer, with the actual code open:
   - Verify the problem is real against the cited code.
   - If the code contradicts the claim, drop the finding.
   - Check if multiple reviewers flagged the same or overlapping issue (consensus).
5. Deduplicate findings that overlap across reviewers. When merging, keep the clearest description and carry forward all originating \`model\` ids in \`sources\`.
6. Rank remaining findings by severity.
7. Preserve questions that are substantive and non-redundant, attributing each to the originating reviewer(s) via \`sources\`.

If the input file is missing, empty, or contains no reviewer outputs, emit an object with empty \`findings\`/\`questions\`, a \`summary\` explaining that no reviews were available, and an empty \`reviewerAgreement\`.

## Guidelines
- Keep consensus findings (flagged by 2+ reviewers) unless clearly wrong.
- Keep solo findings that are well-reasoned and cite specific code.
- Drop stylistic nitpicks that don't affect correctness or security.
- For speculative findings, bias toward keeping them if they cite specific code.
- When reviewers flag different aspects of the same bug, merge into one finding.
- Assign \`severity\` based on your own code verification, not the reviewers' ratings.
- When reviewers disagree on severity, pick based on your own verification.
- Credit the originating model(s) for each finding in \`sources\` (one or more strings matching the reviewer \`model\` ids).
- Only judge findings the reviewers raised — do not introduce new issues.

## Sequence diagram policy
- If 2 or more reviewers included a \`sequenceDiagram\`, pick the one that most accurately reflects the code (verify against the files you read), or merge them if they cover complementary parts of the flow. Emit the chosen Mermaid source as \`sequenceDiagram\`.
- If fewer than 2 reviewers included a diagram, omit the \`sequenceDiagram\` field entirely.

## Output format

Return **only** a single JSON object. No prose before or after. No Markdown code fences. The response must parse as JSON on its own.

Shape:

\`\`\`
{
  "summary": string,              // 2-4 sentence overall assessment based on reviewer consensus
  "findings": Finding[],          // [] if nothing survived judging
  "questions": Question[],        // [] if none
  "sequenceDiagram"?: string,     // Mermaid source (see Sequence diagram policy); omit when not applicable
  "reviewerAgreement": string     // 1-2 sentences on where reviewers agreed and where they diverged
}

Finding = {
  "severity": "critical" | "high" | "medium" | "low",
  "file": string,
  "line"?: number,
  "endLine"?: number,
  "description": string,
  "fix"?: string,
  "sources": string[]             // reviewer model id(s) that flagged this finding; at least one
}

Question = {
  "text": string,
  "sources": string[]             // reviewer model id(s) that raised this question; at least one
}
\`\`\`

Severity guidance (apply after your own verification):
- \`critical\` — security issues, data loss, silent corruption
- \`high\` — bugs or incorrect behavior under normal use
- \`medium\` — performance, maintainability, consistency issues
- \`low\` — style or minor issues

The \`sequenceDiagram\` value, when present, is the Mermaid source **without** surrounding triple backticks. Example:

\`\`\`
"sequenceDiagram\\n    Client->>Server: request\\n    Server-->>Client: response"
\`\`\`

If nothing survives judging, emit \`"findings": []\` and \`"questions": []\` with a \`summary\` explaining the outcome and a \`reviewerAgreement\` describing agreement/divergence among the inputs.

Return only the JSON object.
`;

export const REVIEW_PROMPT =
  `You are generating a pull request review for this repository.

## PR Context
Read these environment variables for context:
- \`PR_NUMBER\`
- \`PR_TITLE\`
- \`PR_URL\`
- \`PR_BASE_REF\`, \`PR_BASE_SHA\`
- \`PR_HEAD_REF\`, \`PR_HEAD_SHA\`
- \`REVIEW_PLAN_FILE\` (defaults to \`pi-review-plan.txt\`)

## Steps
1. Parse \`REVIEW_PLAN_FILE\` to identify:
   - Files to review (new and modified)
   - Files they import or call, and existing files that solve a similar problem
   - Architectural choices that deviate from existing patterns
   - Focus areas (contracts, correctness, security, consistency)
   - Sequence diagram decision (required | optional)

2. Read all files in parallel:
   - Read \`AGENTS.md\` if present.
   - Read all files listed in the review plan (new, modified, comparisons, dependencies).
   - When line ranges are specified (e.g., \`file:100-150\`), read only those ranges.
   - Do not read listed files one at a time.
   - If \`REVIEW_PLAN_FILE\` is missing, continue using the PR diff directly.

3. Review only the PR delta, using context files from the review plan:
   - **Contracts**: Do interfaces with existing code match? (function signatures, SQL, serialization, expected behavior of called code)
   - **Correctness**: Logic errors, edge cases, error handling
   - **Security**: Auth handling, input validation, secret leakage
   - **Performance**: Unnecessary allocations, N+1 queries, blocking calls in async code, algorithmic complexity
   - **Consistency**: Compare against similar implementations and codebase patterns

## Diagram policy
Use the review plan's \`Sequence diagram\` decision:
- If \`Decision: required\`, include a Mermaid sequence diagram (see output format).
- If \`Decision: optional\`, omit the \`sequenceDiagram\` field.
- If the plan is missing or has no decision, include a diagram only when the PR changes meaningful runtime/control/data flow.

## Output format

Return **only** a single JSON object. No prose before or after. No Markdown code fences. The response must parse as JSON on its own.

Shape:

\`\`\`
{
  "summary": string,              // 2-4 sentence overall assessment
  "findings": Finding[],          // one entry per distinct issue; [] if none
  "questions": Question[],        // substantive clarifications; [] if none
  "sequenceDiagram"?: string      // Mermaid source (see Diagram policy); omit the field entirely if not applicable
}

Finding = {
  "severity": "critical" | "high" | "medium" | "low",
  "file": string,                 // repo-relative path, required
  "line"?: number,                // 1-based start line of the issue, if applicable
  "endLine"?: number,             // inclusive end line for ranges
  "description": string,          // what is wrong and why it matters (impact)
  "fix"?: string,                 // concrete suggested change, if applicable
  "sources": []                   // always empty here; the judge populates this
}

Question = {
  "text": string,
  "sources": []                   // always empty here; the judge populates this
}
\`\`\`

Severity guidance:
- \`critical\` — security issues, data loss, silent corruption
- \`high\` — bugs or incorrect behavior under normal use
- \`medium\` — performance, maintainability, consistency issues
- \`low\` — style or minor issues

The \`sequenceDiagram\` value, when present, is the Mermaid source **without** surrounding triple backticks. Example:

\`\`\`
"sequenceDiagram\\n    Client->>Server: request\\n    Server-->>Client: response"
\`\`\`

One finding per distinct issue. Do not combine issues. Do not emit findings that aren't anchored to a specific \`file\`.

If nothing is wrong, emit \`"findings": []\` and \`"questions": []\` with a brief positive \`summary\`.

Return only the JSON object.
`;

export const PROMPTS: Record<string, string> = {
  "gen-review-plan": GEN_REVIEW_PLAN_PROMPT,
  "judge": JUDGE_PROMPT,
  "review": REVIEW_PROMPT,
};
